InvestLink/Controllers/LicenseController.cs
using AutoMapper;
using InvestLink_BLL.Interfaces;
using InvestLink_BLL.Models;
using InvestLink_BLL.Repository;
using InvestLink_DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using NToastNotify;
using System.ComponentModel;
using License = InvestLink_DAL.Entities.License;



namespace InvestLink.Controllers
{
    public class LicenseController : Controller
    {
        #region Fields



        private readonly IProject project;
        private readonly IMapper mapper;
        private readonly ILicense license;
        private readonly IProjectCoordinator projectcoordinator;
        private readonly IEmployee employee;
        private readonly IToastNotification toastNotification;
        private readonly UserManager<IdentityUser> userManager;
        #endregion

        //-----------------------------------------
        #region Ctor
        public LicenseController(IProject project, IMapper mapper, ILicense license, IProjectCoordinator projectcoordinator, IEmployee employee, IToastNotification toastNotification, UserManager<IdentityUser> userManager)
        {
            this.project = project;
            this.mapper = mapper;
            this.license = license;
            this.projectcoordinator = projectcoordinator;
            this.employee = employee;
            this.toastNotification = toastNotification;
            this.userManager = userManager;

        }

        #endregion
        //--------------------------------------------------

        #region Actions
        [Authorize(Roles = "Investor,Admin,HeadOfServices")]
        public async Task<IActionResult> Index()
        {
           

            return View();
        }
      

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(LicenseVM obj)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    var data = mapper.Map<License>(obj);

                    await license.CreateAsync(data);
                    return RedirectToAction("Index");
                }
                TempData["Meesage"] = "validation Error";
                toastNotification.AddErrorToastMessage(" يرجى التحقق من البيانات");
                return View(obj);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                toastNotification.AddErrorToastMessage("حدث خطأ غير متوقع.");
                return View(obj);
            }

        }
        
     


        public async Task<IActionResult> Details(int Id)
        {
            var data = await license.GetByProjectIdAsync(Id);
            if (data == null)
            {
                TempData["Message"] = "الرخصة غير موجودة";
                return RedirectToAction("Index");
            }
            var result = mapper.Map<LicenseVM>(data);

            return View(result);
        }
       


        [Authorize(Roles = "HeadOfServices,Admin")]
        public async Task<IActionResult> Expiredlicenses()
        {

            var expiredData = await license.GetExpiredLicensesAsync();

            var result = mapper.Map<IEnumerable<LicenseVM>>(expiredData);
          
            var coordinators = await userManager.GetUsersInRoleAsync("FollowUpEmployee");
            var emailsList = coordinators.Select(u => u.Email).ToList();

            //   استدعاء الدالة تجيب في ايميل
            var employees = await employee.GetEmployeesByEmailsAsync(emailsList);

            ViewBag.EmployeesList = new SelectList(employees, "Id", "Name");
           
            return View(result);
        }

        [Authorize(Roles = "HeadOfServices")]
        [HttpPost]
        public async Task<IActionResult> SendReportRequest(int ProjectId, int employeeId)
        {
            var pc = await projectcoordinator.GetByIdAsync(ProjectId, employeeId);
            var lastPc = await projectcoordinator.GetByProjectIdAsync(ProjectId);
            if (pc == lastPc && pc != null)
            {
                toastNotification.AddErrorToastMessage("الموظف معين بالفعل لهذا المشروع.");
                return RedirectToAction("Expiredlicenses");
            }
            else if (pc != null)
            {
                await projectcoordinator.DeleteAsync(pc);
            }
            InvestLink_DAL.Entities.ProjectCoordinator obj = new InvestLink_DAL.Entities.ProjectCoordinator();
            obj.ProjectId = ProjectId;
            obj.EmployeeId = employeeId;
            obj.StartDate = DateTime.Now;
            obj.EndDate = DateTime.Now.AddMonths(3);

            await projectcoordinator.CreateAsync(obj);
            toastNotification.AddSuccessToastMessage("تم تعيين الموظف للمشروع بنجاح.");
            
            return RedirectToAction("Expiredlicenses");
        }

    }
}

#endregion

InvestLink/Controllers/ProjectController.cs
using AutoMapper;
using Humanizer;
using InvestLink_BLL.Helper;
using InvestLink_BLL.Interfaces;
using InvestLink_BLL.Models;
using InvestLink_BLL.Repository;
using InvestLink_DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Evaluation;
using Microsoft.CodeAnalysis;
using NToastNotify;
using System.Threading.Tasks;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Project = InvestLink_DAL.Entities.Project;

namespace InvestLink.Controllers
{
    public class ProjectController : Controller
    {
        #region Fields


        private readonly IProject project;
        private readonly IMapper mapper;
        private readonly ILicense license;
        private readonly INationality nationality;
        private readonly IInvestor investor;
        private readonly IProjectInvestor projectinvestor;
        private readonly IToastNotification toastNotification;
        private readonly ICoordinatorReport coordinatorReport;
        private readonly IProjectCoordinator projectcoordinator;



        #endregion

        //-----------------------------------------
        #region Ctor
        public ProjectController(IProject project, IMapper mapper, ILicense license, INationality nationality, IInvestor investor, IProjectInvestor projectinvestor, IToastNotification toastNotification, ICoordinatorReport coordinatorReport, IProjectCoordinator projectcoordinator)
        {
            this.project = project;
            this.mapper = mapper;
            this.license = license;
            this.nationality = nationality;
            this.investor = investor;
            this.projectinvestor = projectinvestor;
            this.toastNotification = toastNotification;
            this.coordinatorReport = coordinatorReport;
            this.projectcoordinator = projectcoordinator;
        }
        #endregion
        //--------------------------------------------------

        #region Actions
        [Authorize(Roles = "Investor,Admin,HeadOfServices")]
        public async Task<IActionResult> Index()
        {

            return View();
        }

        [Authorize(Roles = "Investor")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var nat = await nationality.GetAllAsync();
            ViewBag.NationalityList = new SelectList(nat, "Id", "Name");
            return View();
        }

        [Authorize(Roles = "Investor")]
        [HttpPost]
        public async Task<IActionResult> Create(Investor_ProjectVM obj)
        {
            try
            {
                
                
                if (ModelState.IsValid == true)
                {
                    var LegalBodyName = FileUpLoader.UploaderFile(obj.Project.LegalBodyFile, "Doc");
                    obj.Project.LegalBodyName = LegalBodyName;

                    obj.Project.State = "تم استلام";

                    var Project_info = mapper.Map<Project>(obj.Project);


                    var Project_info_Id = await project.CreateAsync(Project_info);


                    if (obj.Investors != null )
                    {
                        foreach (var item in obj.Investors)
                        {
                           
                            var CaredName = FileUpLoader.UploaderFile(item.CImage, "Doc");
                            item.CaredName = CaredName;
                            var PassportName = FileUpLoader.UploaderFile(item.PImage, "Doc");
                            item.PassportName = PassportName;

                            var submittedInvestor = await investor.GetByEmailAsync(item.Email);

                                int investorId;
                                if (submittedInvestor != null)
                                {
                                    //existing investor
                                    investorId = submittedInvestor.Id;

                                }
                                else
                                {
                                    //New investor
                                    var newInvestor = mapper.Map<Investor>(item);
                                    investorId = await investor.CreateAsync(newInvestor);
                                }

                                var Link = new ProjectInvestor
                                {
                                    ProjectId = Project_info_Id,
                                    InvestorId = investorId
                                };

                                await projectinvestor.CreateAsync(Link);
                        }

                        // تسجيل المستثمر المقدم للطلب
                        var Link1 = new ProjectInvestor
                        {
                            ProjectId = Project_info_Id,
                            InvestorId = obj.SubmitedInvestorId
                        };
                        await projectinvestor.CreateAsync(Link1);

                    }
                    toastNotification.AddSuccessToastMessage("تم تقديم طلب بنجاح.");
                    return RedirectToAction("Index");
                    }
                    TempData["Message"] = "validation Error";
                toastNotification.AddErrorToastMessage("يرجى تحقق من بيانات.");
                var nat = await nationality.GetAllAsync(); // أو أي دالة تجلب البيانات عندك
                ViewBag.NationalityList = new SelectList(nat, "Id", "Name");
                return View(obj);
                }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("حدث خطأ غير متوقع.");
                TempData["Message"] = ex.Message;
                return View(obj);
            }
        }
         

        
        public async Task<IActionResult> Details(int Id)
        {
            var data = await project.GetByIdAsync(Id);
            var result = mapper.Map<Investor_ProjectVM>(data);
            var nat = mapper.Map<IEnumerable<NationalityVM>>(await nationality.GetAllAsync());
            ViewBag.NationalityList = new SelectList(nat, "Id", "Name");

            return View(result);
        }

        [Authorize(Roles = "Admin,HeadOfServices")]
        [HttpGet]
        public async Task<IActionResult> NewRequests()
        {

            var data = await project.GetByStateAsync("تم استلام");
            var result = mapper.Map<IEnumerable<ProjectVM>>(data);
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> SendToAdmin(int Id)
        {
            var request = await project.GetByIdAsync(Id);

            request.State = "قيد المراجعة من الإدارة";
            await project.UpdateAsync(request);

            
            toastNotification.AddSuccessToastMessage("تم إرسال الطلب إلى الإدارة بنجاح.");
            return RedirectToAction("RequestsReferredtomanagement");

        }


        [HttpPost]
        public async Task<IActionResult> Reject(int Id)
        {
            var request = await project.GetByIdAsync(Id);


            request.State = "مرفوض";
            await project.UpdateAsync(request);
            toastNotification.AddSuccessToastMessage("تم رفض الطلب .");
           
            return RedirectToAction("RejectedRequests");
        }
        [HttpGet]
        public async Task<IActionResult> RejectedRequests()
        {
            var data = await project.GetByStateAsync("مرفوض");
            var result = mapper.Map<IEnumerable<ProjectVM>>(data);
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> RequestsReferredtomanagement()
        {
            var data = await project.GetByStateAsync("قيد المراجعة من الإدارة");
            var result = mapper.Map<IEnumerable<ProjectVM>>(data);
            return View(result);
        }
        [HttpGet]
        [Authorize(Roles = "Admin,HeadOfServices,Investor")]
        public async Task<IActionResult> ApproveFinal()
        {

            var data = await project.GetByStateAsync("معتمد");

            var result = mapper.Map<IEnumerable<ProjectVM>>(data);
            return View(result);
        }


      
        [HttpPost]
        public async Task<IActionResult> ApproveFinal(int Id)
        {         
        try {
            var request = await project.GetByIdAsync(Id);

            request.State = "معتمد";
            await project.UpdateAsync(request);
           InvestLink_DAL.Entities.License obj = new InvestLink_DAL.Entities.License();

            obj.ProjectId = request.Id;
            obj.CreatedDate = DateTime.Now;
            obj.ExpireDate = DateTime.Now.AddMinutes(2);
            obj.Type = "رخصة استثمارية";
            obj.LicenseNumber = $"{DateTime.Now.Year}-LIC";
            await license.CreateAsync(obj);
                toastNotification.AddSuccessToastMessage("تم اعتماد الطلب وإصدار الرخصة بنجاح .");
          
           return RedirectToAction("ApproveFinal");

            }

            catch (Exception ex)
            {
                toastNotification.AddSuccessToastMessage("حدث خطا اثناء الاعتماد .");
                
                return RedirectToAction("ApproveFinal");
            }
          
        }
        //[HttpPost]
        //public async Task<IActionResult> RejectFinal(int Id)
        //{
        //    var request = await project.GetByIdAsync(Id);

        //    request.State = "مرفوض ";
        //    await project.UpdateAsync(request);
        //    toastNotification.AddSuccessToastMessage("تم رفض الطلب نهائياً  .");
          
        //    return RedirectToAction("Details", new { Id });
        //}

      
    }
    
}


#endregion

InvestLink/Views/Project/ApproveFinal.cshtml
@using InvestLink_BLL.Interfaces
@using InvestLink_DAL.Entities
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> signInManager
@inject IProject iproject;
@inject IProjectInvestor iprojectInvestor
@inject IInvestor iInvestor
@inject UserManager<IdentityUser> userManager


@{
    ViewBag.Title = "ApproveFinal";
}

@{
    var user = await signInManager.UserManager.GetUserAsync(signInManager.Context.User);
    var email = await signInManager.UserManager.GetEmailAsync(user);
    IEnumerable<Project> projects;
    @if (User.IsInRole("Investor"))
    {
        var investor = await iInvestor.GetByEmailAsync(email);
        var investorId = investor.Id;
        var projectInvestors = await iprojectInvestor.GetAllAsync(investorId);
        projects = await iproject.GetAllAsyncByFiltter(projectInvestors, "معتمد");


    }
    else
    {
        projects = await iproject.GetAllAsync();
    }
}


<div class="container-fluid">
    <!-- Page Header -->
    

    <!-- Approved Projects Table Card -->
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table mb-0 table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">اسم المشروع</th>
                            <th scope="col">تاريخ تقديم الطلب</th>
                            <th scope="col">تفاصيل المشروع</th>

                           
                                <th scope="col">رخصة المشروع</th>
                            

                            
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int Count = 0;
                        }
                        @foreach (var Item in projects)
                        {
                            Count++;
                            <tr>
                                @* 1. عداد *@
                                <th scope="row">
                                    <div style="width: 40px; height: 40px; background: linear-gradient(135deg, rgba(79, 172, 254, 0.1) 0%, rgba(0, 242, 254, 0.1) 100%); border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: 700; color: #4facfe;">
                                        @Count
                                    </div>
                                </th>

                                @* 2. اسم المشروع *@
                                <td style="font-weight: 600; color: #2d3748;">@Item.Name</td>

                                @* 3. التاريخ *@
                                <td style="color: #718096;">@Item.CreationData</td>

                                @* 4. تفاصيل المشروع *@
                                <td>
                                    <a asp-controller="Project" asp-action="Details" asp-route-Id="@Item.Id"
                                       class="btn btn-sm"
                                       style="background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%); border: none; border-radius: 10px; padding: 0.5rem 1rem; color: #667eea; font-weight: 600; transition: all 0.3s ease;"
                                       onmouseover="this.style.background='linear-gradient(135deg, #667eea 0%, #764ba2 100%)'; this.style.color='white';"
                                       onmouseout="this.style.background='linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)'; this.style.color='#667eea';">
                                        <ion-icon name="eye-outline" style="vertical-align: middle; margin-left: 0.25rem;"></ion-icon>
                                        عرض التفاصيل
                                    </a>
                                </td>
                               
                                    <td>                                       
                                            <a asp-controller="License" asp-action="Details" asp-route-Id="@Item.Id"
                                               class="btn btn-sm"
                                               style="background: linear-gradient(135deg, rgba(17, 153, 142, 0.1) 0%, rgba(56, 239, 125, 0.1) 100%); border: none; border-radius: 10px; padding: 0.5rem 1rem; color: #11998e; font-weight: 600; transition: all 0.3s ease;"
                                               onmouseover="this.style.background='linear-gradient(135deg, #11998e 0%, #38ef7d 100%)'; this.style.color='white';"
                                               onmouseout="this.style.background='linear-gradient(135deg, rgba(17, 153, 142, 0.1) 0%, rgba(56, 239, 125, 0.1) 100%)'; this.style.color='#11998e';">
                                                <ion-icon name="eye-outline" style="vertical-align: middle; margin-left: 0.25rem;"></ion-icon>
                                                عرض التفاصيل
                                            </a>                                      
                                    </td>
                               

                               

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

InvestLink/Views/Project/Index.cshtml
@using InvestLink_BLL.Interfaces
@using InvestLink_BLL.Models
@using InvestLink_DAL.Entities
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> signInManager
@inject IProject iproject;
@inject IProjectInvestor iprojectInvestor
@inject IInvestor iInvestor
@inject UserManager<IdentityUser> userManager
@{
    ViewBag.Title = "Index ";
}

@{
    var user = await signInManager.UserManager.GetUserAsync(signInManager.Context.User);
    var email = await signInManager.UserManager.GetEmailAsync(user);
    IEnumerable<Project> projects;
    @if (User.IsInRole("Investor"))
    {
        var investor =await iInvestor.GetByEmailAsync(email);
        var investorId = investor.Id;
        var projectInvestors = await iprojectInvestor.GetAllAsync(investorId);
        projects = await iproject.GetAllAsyncByFiltter(projectInvestors , "تم استلام");

    }
    else
    {
        projects = await iproject.GetAllAsync();
    }
}

<div class="container-fluid">
    <!-- Page Header -->
   

    <!-- Projects Table Card -->
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table mb-0 table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">اسم المشروع</th>
                            <th scope="col">تاريخ الإنشاء</th>
                            <th scope="col">حالة الطلب</th>
                            <th scope="col">التفاصيل</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int Count = 0;
                        }
                        @foreach (var Item in projects)
                        {
                            Count++;
                            <tr>
                                <th scope="row">
                                    <div style="width: 40px; height: 40px; background: linear-gradient(135deg, rgba(79, 172, 254, 0.1) 0%, rgba(0, 242, 254, 0.1) 100%); border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: 700; color: #4facfe;">
                                        @Count
                                    </div>
                                </th>
                                <td style="font-weight: 600; color: #2d3748;">@Item.Name</td>
                                <td style="color: #718096;">@Item.CreationData</td>
                                <td>
                                    @{
                                        var badgeClass = "badge-primary";
                                        var badgeStyle = "background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);";
                                        
                                        if (Item.State == "معتمد")
                                        {
                                            badgeStyle = "background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);";
                                        }
                                        else if (Item.State == "مرفوض")
                                        {
                                            badgeStyle = "background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);";
                                        }
                                        else if (Item.State == "قيد المراجعة")
                                        {
                                            badgeStyle = "background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);";
                                        }
                                    }
                                    <span class="badge" style="@badgeStyle padding: 0.5rem 1rem; border-radius: 20px; font-weight: 600;">@Item.State</span>
                                </td>
                                <td>
                                    <a asp-controller="Project" asp-action="Details" asp-route-Id="@Item.Id" 
                                       class="btn btn-sm" 
                                       style="background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%); border: none; border-radius: 10px; padding: 0.5rem 1rem; color: #667eea; font-weight: 600; transition: all 0.3s ease;"
                                       onmouseover="this.style.background='linear-gradient(135deg, #667eea 0%, #764ba2 100%)'; this.style.color='white';"
                                       onmouseout="this.style.background='linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)'; this.style.color='#667eea';">
                                        <ion-icon name="eye-outline" style="vertical-align: middle; margin-left: 0.25rem;"></ion-icon>
                                        عرض التفاصيل
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>




<!-- JS Files-->
<script src="assets/js/jquery.min.js"></script>
<script src="assets/plugins/simplebar/js/simplebar.min.js"></script>
<script src="assets/plugins/metismenu/js/metisMenu.min.js"></script>
<script src="assets/js/bootstrap.bundle.min.js"></script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<!--plugins-->
<script src="assets/plugins/perfect-scrollbar/js/perfect-scrollbar.js"></script>

<!-- Main JS-->
<script src="assets/js/main.js"></script>



<!-- JS Files-->
<script src="assets/js/jquery.min.js"></script>
<script src="assets/plugins/simplebar/js/simplebar.min.js"></script>
<script src="assets/plugins/metismenu/js/metisMenu.min.js"></script>
<script src="assets/js/bootstrap.bundle.min.js"></script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<!--plugins-->
<script src="assets/plugins/perfect-scrollbar/js/perfect-scrollbar.js"></script>
<script src="assets/plugins/apexcharts-bundle/js/apexcharts.min.js"></script>
<script src="assets/plugins/easyPieChart/jquery.easypiechart.js"></script>
<script src="assets/plugins/chartjs/chart.min.js"></script>
<script src="assets/js/index.js"></script>
<!-- Main JS-->
<script src="assets/js/main.js"></script>

InvestLink/Views/Project/NewRequests.cshtml
@model IEnumerable<InvestLink_BLL.Models.ProjectVM>
@{
    ViewBag.Title = "NewRequests ";
}

<div class="container-fluid">
    <!-- Page Header -->
   

    <!-- Requests Table Card -->
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table mb-0 table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">اسم المشروع</th>
                            <th scope="col">تاريخ الإنشاء</th>
                            <th scope="col">التفاصيل</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int Count = 0;
                        }
                        @foreach (var Item in Model)
                        {
                            Count++;
                            <tr>
                                <th scope="row">
                                    <div style="width: 40px; height: 40px; background: linear-gradient(135deg, rgba(79, 172, 254, 0.1) 0%, rgba(0, 242, 254, 0.1) 100%); border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: 700; color: #4facfe;">
                                        @Count
                                    </div>
                                </th>
                                <td style="font-weight: 600; color: #2d3748;">@Item.Name</td>
                                <td style="color: #718096;">@Item.CreationData</td>
                                <td>
                                    <a asp-controller="Project" asp-action="Details" asp-route-Id="@Item.Id"
                                       class="btn btn-sm"
                                       style="background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%); border: none; border-radius: 10px; padding: 0.5rem 1rem; color: #667eea; font-weight: 600; transition: all 0.3s ease;"
                                       onmouseover="this.style.background='linear-gradient(135deg, #667eea 0%, #764ba2 100%)'; this.style.color='white';"
                                       onmouseout="this.style.background='linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)'; this.style.color='#667eea';">
                                        <ion-icon name="eye-outline" style="vertical-align: middle; margin-left: 0.25rem;"></ion-icon>
                                        عرض التفاصيل
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>