InvestLink/Controllers/CoordinatorReportController.cs
using AutoMapper;
using InvestLink_BLL.Helper;
using InvestLink_BLL.Interfaces;
using InvestLink_BLL.Models;
using InvestLink_BLL.Repository;
using InvestLink_DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using NToastNotify;

namespace InvestLink.Controllers
{
    public class CoordinatorReportController : Controller
    {
        #region Fields


        private readonly ICoordinatorReport coordinatorReport;
        private readonly ILicense license;
        private readonly IProject project;
        private readonly IProjectCoordinator projectcoordinator;
        private readonly IMapper mapper;
        private readonly IToastNotification toastNotification;



        #endregion

        //-----------------------------------------
        #region Ctor
        public CoordinatorReportController(ICoordinatorReport coordinatorReport, ILicense license, IProject project, IProjectCoordinator projectcoordinator, IMapper mapper, IToastNotification toastNotification)
        {
            this.coordinatorReport = coordinatorReport;
            this.license = license;
            this.project = project;
            this.projectcoordinator = projectcoordinator;
            this.mapper = mapper;
            this.toastNotification = toastNotification;
        }

        #endregion
        //--------------------------------------------------

        #region Actions

        public async Task<IActionResult> Index()
        {
            var data = await coordinatorReport.GetAllAsync();

            var result = mapper.Map<IEnumerable<CoordinatorReportVM>>(data);
            return View(result);
        }

        public async Task<IActionResult> ReCreateLicense(int projectId)
        {

            var _project = await project.GetByIdAsync(projectId);

            _project.State = "معتمد";
            await project.UpdateAsync(_project);

            License obj = new License();
            obj.ProjectId = projectId;
            obj.ExpireDate = DateTime.Now.AddMinutes(2);
            obj.Type = "مزاولة";
            obj.CreatedDate = DateTime.Now;
            obj.LicenseNumber = $"{DateTime.Now.Year}-LIC";

            await license.CreateAsync(obj);
            toastNotification.AddSuccessToastMessage("تم  تجديد رخصه بنجاح.");
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> RejectLicenses(int projectId)
        {

            var _project = await project.GetByIdAsync(projectId);

            _project.State = "سحب الترخيص";
            await project.UpdateAsync(_project);
            toastNotification.AddErrorToastMessage("تم سحب الترخيص وعدم التجديد.");
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> RejectedLicenses()
        {



            var _project = await project.GetByStateAsync("سحب الترخيص");
            var data = mapper.Map<IEnumerable<ProjectVM>>(_project);

            return View(data);


        }
        [HttpGet]
        public IActionResult Create()
        {

   
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CoordinatorReportVM obj)
        {
            try
            {

                var cr = await projectcoordinator.GetByIdAsync(obj.ProjectId, obj.EmployeeId);
                obj.ProjectCoordinatorId = cr.Id;

                var ImageName = FileUpLoader.UploaderFile(obj.Image, "Doc");
                obj.ImageName = ImageName;
                if (ModelState.IsValid == true)
                {
                    obj.Status = "صادر";

                    obj.CreationData = DateTime.Now;
                    var data = mapper.Map<CoordinatorReport>(obj);

                    await coordinatorReport.CreateAsync(data);
                    return RedirectToAction("Index");
                }
                TempData["Meesage"] = "validation Error";
                toastNotification.AddErrorToastMessage(" يرجى التحقق من البيانات");
                return View(obj);
            }

            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                ModelState.AddModelError("", ex.Message);
                toastNotification.AddErrorToastMessage("حدث خطأ غير متوقع.");
                return View(obj);
            }


        }
        [HttpGet]
        public async Task<IActionResult> Update(int Id)
        {

            var data = await coordinatorReport.GetByIdAsync(Id);
            var result = mapper.Map<CoordinatorReportVM>(data);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CoordinatorReportVM obj)
        {
            try
            {
                if (obj.Image != null)
                {
                    var ImageName = FileUpLoader.UploaderFile(obj.Image, "Doc");
                    obj.ImageName = ImageName;
                }
                    
                if (ModelState.IsValid == true)
                {
                    obj.Status = "محدث";
                    obj.IsUpdated= true;
                    obj.UpdatedDate = DateTime.Now;
                    var data = mapper.Map<CoordinatorReport>(obj);
                    await coordinatorReport.UpdateAsync(data);
                    toastNotification.AddSuccessToastMessage("تم  تعديل بيانات بنجاح.");
                    return RedirectToAction("Index");
                }
                TempData["Message"] = "validation Error";
                toastNotification.AddErrorToastMessage(" يرجى التحقق من البيانات");
                return View(obj);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                
                toastNotification.AddErrorToastMessage("حدث خطأ غير متوقع.");
                return View(obj);
            }
        }



        public async Task<IActionResult> Details(int Id)
        {

            var data = await coordinatorReport.GetByIdAsync(Id);
            var result = mapper.Map<CoordinatorReportVM>(data);

            return View(result);
        }

    }
}

#endregion

InvestLink/Controllers/ProjectController.cs
using AutoMapper;
using Humanizer;
using InvestLink_BLL.Helper;
using InvestLink_BLL.Interfaces;
using InvestLink_BLL.Models;
using InvestLink_BLL.Repository;
using InvestLink_DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Evaluation;
using Microsoft.CodeAnalysis;
using NToastNotify;
using System.Threading.Tasks;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Project = InvestLink_DAL.Entities.Project;

namespace InvestLink.Controllers
{
    public class ProjectController : Controller
    {
        #region Fields


        private readonly IProject project;
        private readonly IMapper mapper;
        private readonly ILicense license;
        private readonly INationality nationality;
        private readonly IInvestor investor;
        private readonly IProjectInvestor projectinvestor;
        private readonly IToastNotification toastNotification;
        private readonly ICoordinatorReport coordinatorReport;
        private readonly IProjectCoordinator projectcoordinator;



        #endregion

        //-----------------------------------------
        #region Ctor
        public ProjectController(IProject project, IMapper mapper, ILicense license, INationality nationality, IInvestor investor, IProjectInvestor projectinvestor, IToastNotification toastNotification, ICoordinatorReport coordinatorReport, IProjectCoordinator projectcoordinator)
        {
            this.project = project;
            this.mapper = mapper;
            this.license = license;
            this.nationality = nationality;
            this.investor = investor;
            this.projectinvestor = projectinvestor;
            this.toastNotification = toastNotification;
            this.coordinatorReport = coordinatorReport;
            this.projectcoordinator = projectcoordinator;
        }
        #endregion
        //--------------------------------------------------

        #region Actions
        [Authorize(Roles = "Investor,Admin,HeadOfServices")]
        public async Task<IActionResult> Index()
        {

            return View();
        }

        [Authorize(Roles = "Investor")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var nat = await nationality.GetAllAsync();
            ViewBag.NationalityList = new SelectList(nat, "Id", "Name");
            return View();
        }

        [Authorize(Roles = "Investor")]
        [HttpPost]
        public async Task<IActionResult> Create(Investor_ProjectVM obj)
        {
            try
            {
                
                
                if (ModelState.IsValid == true)
                {
                    var LegalBodyName = FileUpLoader.UploaderFile(obj.Project.LegalBodyFile, "Doc");
                    obj.Project.LegalBodyName = LegalBodyName;

                    obj.Project.State = "تم استلام";

                    var Project_info = mapper.Map<Project>(obj.Project);


                    var Project_info_Id = await project.CreateAsync(Project_info);


                    if (obj.Investors != null )
                    {
                        foreach (var item in obj.Investors)
                        {
                           
                            var CaredName = FileUpLoader.UploaderFile(item.CImage, "Doc");
                            item.CaredName = CaredName;
                            var PassportName = FileUpLoader.UploaderFile(item.PImage, "Doc");
                            item.PassportName = PassportName;

                            var submittedInvestor = await investor.GetByEmailAsync(item.Email);

                                int investorId;
                                if (submittedInvestor != null)
                                {
                                    //existing investor
                                    investorId = submittedInvestor.Id;

                                }
                                else
                                {
                                    //New investor
                                    var newInvestor = mapper.Map<Investor>(item);
                                    investorId = await investor.CreateAsync(newInvestor);
                                }

                                var Link = new ProjectInvestor
                                {
                                    ProjectId = Project_info_Id,
                                    InvestorId = investorId
                                };

                                await projectinvestor.CreateAsync(Link);
                        }

                        // تسجيل المستثمر المقدم للطلب
                        var Link1 = new ProjectInvestor
                        {
                            ProjectId = Project_info_Id,
                            InvestorId = obj.SubmitedInvestorId
                        };
                        await projectinvestor.CreateAsync(Link1);

                    }
                    toastNotification.AddSuccessToastMessage("تم تقديم طلب بنجاح.");
                    return RedirectToAction("Index");
                    }
                    TempData["Message"] = "validation Error";
                toastNotification.AddErrorToastMessage("يرجى تحقق من بيانات.");
                var nat = await nationality.GetAllAsync(); // أو أي دالة تجلب البيانات عندك
                ViewBag.NationalityList = new SelectList(nat, "Id", "Name");
                return View(obj);
                }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("حدث خطأ غير متوقع.");
                TempData["Message"] = ex.Message;
                return View(obj);
            }
        }
         

        
        public async Task<IActionResult> Details(int Id)
        {
            var data = await project.GetByIdAsync(Id);
            var result = mapper.Map<Investor_ProjectVM>(data);
            var nat = mapper.Map<IEnumerable<NationalityVM>>(await nationality.GetAllAsync());
            ViewBag.NationalityList = new SelectList(nat, "Id", "Name");

            return View(result);
        }

        [Authorize(Roles = "Admin,HeadOfServices")]
        [HttpGet]
        public async Task<IActionResult> NewRequests()
        {

            var data = await project.GetByStateAsync("تم استلام");
            var result = mapper.Map<IEnumerable<ProjectVM>>(data);
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> SendToAdmin(int Id)
        {
            var request = await project.GetByIdAsync(Id);

            request.State = "قيد المراجعة من الإدارة";
            await project.UpdateAsync(request);

            
            toastNotification.AddSuccessToastMessage("تم إرسال الطلب إلى الإدارة بنجاح.");
            return RedirectToAction("RequestsReferredtomanagement");

        }


        [HttpPost]
        public async Task<IActionResult> Reject(int Id)
        {
            var request = await project.GetByIdAsync(Id);


            request.State = "مرفوض";
            await project.UpdateAsync(request);
            toastNotification.AddSuccessToastMessage("تم رفض الطلب .");
           
            return RedirectToAction("RejectedRequests");
        }
        [HttpGet]
        public async Task<IActionResult> RejectedRequests()
        {
            var data = await project.GetByStateAsync("مرفوض");
            var result = mapper.Map<IEnumerable<ProjectVM>>(data);
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> RequestsReferredtomanagement()
        {
            var data = await project.GetByStateAsync("قيد المراجعة من الإدارة");
            var result = mapper.Map<IEnumerable<ProjectVM>>(data);
            return View(result);
        }
        [HttpGet]
        [Authorize(Roles = "Admin,HeadOfServices,Investor")]
        public async Task<IActionResult> ApproveFinal()
        {

            var data = await project.GetByStateAsync("معتمد");

            var result = mapper.Map<IEnumerable<ProjectVM>>(data);
            return View(result);
        }


      
        [HttpPost]
        public async Task<IActionResult> ApproveFinal(int Id)
        {         
        try {
            var request = await project.GetByIdAsync(Id);

            request.State = "معتمد";
            await project.UpdateAsync(request);
           InvestLink_DAL.Entities.License obj = new InvestLink_DAL.Entities.License();

            obj.ProjectId = request.Id;
            obj.CreatedDate = DateTime.Now;
            obj.ExpireDate = DateTime.Now.AddMinutes(2);
            obj.Type = "رخصة استثمارية";
            obj.LicenseNumber = $"{DateTime.Now.Year}-LIC";
            await license.CreateAsync(obj);
                toastNotification.AddSuccessToastMessage("تم اعتماد الطلب وإصدار الرخصة بنجاح .");
          
           return RedirectToAction("ApproveFinal");

            }

            catch (Exception ex)
            {
                toastNotification.AddSuccessToastMessage("حدث خطا اثناء الاعتماد .");
                
                return RedirectToAction("ApproveFinal");
            }
          
        }
        //[HttpPost]
        //public async Task<IActionResult> RejectFinal(int Id)
        //{
        //    var request = await project.GetByIdAsync(Id);

        //    request.State = "مرفوض ";
        //    await project.UpdateAsync(request);
        //    toastNotification.AddSuccessToastMessage("تم رفض الطلب نهائياً  .");
          
        //    return RedirectToAction("Details", new { Id });
        //}

      
    }
    
}


#endregion

InvestLink/Views/CoordinatorReport/Create.cshtml
@using InvestLink_BLL.Interfaces
@using InvestLink_DAL.Entities
@using Microsoft.AspNetCore.Identity
@model InvestLink_BLL.Models.CoordinatorReportVM

@inject SignInManager<IdentityUser> signInManager

@inject ICoordinatorReport icoordinatorReport;

@inject IEmployee iEmployee;

@* //----------ProjectId/IEmployeeId----------- *@

@inject IProjectCoordinator iProjectcoordinator;



@{
    ViewBag.Title = "Create";
}
@{

    var user = await signInManager.UserManager.GetUserAsync(signInManager.Context.User);
    var email = await signInManager.UserManager.GetEmailAsync(user);
    var iEmployeeId = iEmployee.GetIdByEmail(email);
}

<div class="card">
    <div class="card-body">
        <div class="border p-3 rounded">
            <h6 class="mb-0 text-uppercase">إضافة تقرير جديد</h6>
            <hr>

        

            <form asp-controller="CoordinatorReport" asp-action="Create" enctype="multipart/form-data" class="row g-3">
                <input type="hidden" asp-for="EmployeeId" value="@iEmployeeId" />
                @* <input type="hidden" asp-for="ProjectCoordinatorId" /> *@

                <div class="col-12 col-lg-6">
                    <label asp-for="ProjectId" class="form-label">اسم المشروع</label>
                    <select class="form-select mb-3" asp-for="ProjectId">
                        @foreach (var item in await iProjectcoordinator.GetAllAsync(iEmployeeId))
                        {
                            <option value="@item.ProjectId"> @item.Project.Name </option>

                        }

                    </select>
                </div>
                <div class="col-12">
                    <label asp-for="Description" class="form-label">الوصف</label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <label asp-for="Image" class="form-label">صورة</label>
                    <input asp-for="Image" class="form-control" type="file" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>




                <div class="col-12">
                    <div class="d-flex justify-content-center gap-2 mt-3">
                        <input type="submit" value="حفظ" class="btn btn-success px-4" />


                        <a asp-action="Index" class="btn btn-secondary btn-sm px-4">الرجوع </a>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

InvestLink/Views/CoordinatorReport/Details.cshtml
@model InvestLink_BLL.Models.CoordinatorReportVM

@{
    ViewBag.Title = "Details";
}

<div class="card">
    <div class="card-body">
        <div class="border p-3 rounded">
            <h6 class="mb-0 text-uppercase">تفاصيل تقرير </h6>
            <hr>

          

            <form asp-controller="CoordinatorReport" asp-action="Details" enctype="multipart/form-data" class="row g-3">

                <input type="hidden" asp-for="Id" />
                <div class="col-12">
                    <label asp-for="Description" class="form-label">الوصف</label>
                    <textarea asp-for="Description" class="form-control"  readonly></textarea>
                    
                </div>

                <div class="col-12 col-lg-12">
                    <label class="form-label">صورة </label>

                    @if (Model != null && !string.IsNullOrEmpty(Model.ImageName))
                    {
                        <div class="mt-2">
                            <a href="@Url.Content("~/Files/Doc/" + Model.ImageName)" target="_blank" class="form-control">
                                <i class='bx bx-show'></i> عرض الملف
                            </a>
                        </div>
                    }
                    else
                    {
                        <input type="text" class="form-control text-muted" value="لا يوجد ملف مرفق" readonly>
                    }
                </div>
         

            
                 
                

               
                <div class="col-6">
                    <div class="d-flex justify-content-start gap-2 mt-3">
                       
                        <a asp-action="Index" class="btn btn-secondary btn-sm px-4">الرجوع </a>

                    </div>
                </div>
            </form>
           
           
        </div>
    </div>
</div>

InvestLink/Views/CoordinatorReport/Index.cshtml
@{
    ViewBag.Title = "Index ";
}

﻿@using InvestLink_BLL.Interfaces
@using InvestLink_DAL.Entities
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> signInManager
@inject ICoordinatorReport icoordinatorReport;
@inject IEmployee iEmployee;



@{
    var user = await signInManager.UserManager.GetUserAsync(signInManager.Context.User);
    var email = await signInManager.UserManager.GetEmailAsync(user);

    // متغير
    IEnumerable<CoordinatorReport> coordinatorReports;
  

    if (User.IsInRole("FollowUpEmployee"))
    {
        var iEmp = await iEmployee.GetByEmailAsync(email);
        var iEmptId = iEmp.Id;


        coordinatorReports = await icoordinatorReport.GetAllAsync(iEmptId);
    }
    else
    {
    coordinatorReports = await icoordinatorReport.GetAllAsync();
    }

}


@*  لموظف المتابعة و رئيس خدمات المستثمرين*@


<hr>
<div class="card">
    <div class="card-body">
        <table class="table mb-0 table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">اسم</th>
                    <th scope="col"> حالة تقرير</th>
    
                    <th scope="col"> الاجراءات</th>
    
                </tr>
            </thead>
            <tbody>
                @{
                    int Count = 0;
                }
                @foreach (var Item in coordinatorReports)
                {
                    if(Item.ProjectCoordinator.Project.State != "سحب الترخيص" && Item.ProjectCoordinator.Project.State != "مرفوض")
                    {
                                Count++;
         <tr>
             <th scope="row"> <div style="width: 40px; height: 40px; background: linear-gradient(135deg, rgba(79, 172, 254, 0.1) 0%, rgba(0, 242, 254, 0.1) 100%); border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: 700; color: #4facfe;">
                             @Count
                         </div></th>

             <td>@Item.ProjectCoordinator.Project.Name</td>
             <td>@Item.Status</td>

             <td>
                 <a asp-controller="CoordinatorReport"
                    asp-action="Details"
                    asp-route-id="@Item.Id"
                       class="btn btn-sm" 
                            style="background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%); border: none; border-radius: 10px; padding: 0.5rem 1rem; color: #667eea; font-weight: 600; transition: all 0.3s ease;"
                            onmouseover="this.style.background='linear-gradient(135deg, #667eea 0%, #764ba2 100%)'; this.style.color='white';"
                            onmouseout="this.style.background='linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)'; this.style.color='#667eea';">
                             <ion-icon name="eye-outline" style="vertical-align: middle; margin-left: 0.25rem;"></ion-icon>
                             عرض التفاصيل
                 </a>
                 

             </td>

          @if (User.IsInRole("HeadOfServices") || User.IsInRole("Admin"))
 {
                 

                     @if(Item.ProjectCoordinator != null)
                     {
                         var projectId = Item.ProjectCoordinator.ProjectId;
                 
                         <td>
                         
                              <a asp-controller="CoordinatorReport"
        asp-action="ReCreateLicense"
        asp-route-projectId="@projectId"
        class="btn btn-info waves-effect">
         <i class="fadeIn animated bx bx-pencil"></i>
     </a>
</td>
    <td>

         <a asp-controller="CoordinatorReport"
            asp-action="RejectLicenses"
            asp-route-projectId="@projectId"
            
            class="btn btn-danger px-4">
             <ion-icon name="lock-closed-outline"></ion-icon>
         </a>
            </td> 
                    }
                    }

           

           
        </tr>
    }

                }
                               
              
        
            
            </tbody>
        </table>
    </div>
</div>

InvestLink/Views/CoordinatorReport/RejectedLicenses.cshtml
@model IEnumerable<InvestLink_BLL.Models.ProjectVM>;

@{
    ViewBag.Title = "Index ";
}









<div class="container-fluid">
    <!-- Page Header -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="d-flex align-items-center">

                <div>
                    <h2 class="gradient-text mb-1" style="font-weight: 700; font-size: 2rem;"> سحب تراخيص</h2>
                    <p class="text-secondary mb-0"></p>
                </div>
            </div>
        </div>
    </div>

    <!-- Rejected Requests Table Card -->
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table mb-0 table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">اسم المشروع</th>
                            <th scope="col">تاريخ الإنشاء</th>
                            <th scope="col">التفاصيل</th>
                            <th scope="col">الإجراءات</th>
                        </tr>
                    </thead>
                  <tbody>
    @{
        int Count = 0;
    }
    @foreach (var Item in Model)
    {
        Count++;
        <tr>
            <th scope="row">
                <div style="width: 40px; height: 40px; background: linear-gradient(135deg, rgba(79, 172, 254, 0.1) 0%, rgba(0, 242, 254, 0.1) 100%); border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: 700; color: #4facfe;">
                    @Count
                </div>
            </th>

        <td style="font-weight: 600; color: #2d3748;">@Item.Name</td>

            <td style="color: #718096;">@Item.CreationData</td>

            <td>
                <a asp-controller="Project" asp-action="Details" asp-route-Id="@Item.Id"
                   class="btn btn-sm"
                   style="background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%); border: none; border-radius: 10px; padding: 0.5rem 1rem; color: #667eea; font-weight: 600; transition: all 0.3s ease;"
                   onmouseover="this.style.background='linear-gradient(135deg, #667eea 0%, #764ba2 100%)'; this.style.color='white';"
                   onmouseout="this.style.background='linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)'; this.style.color='#667eea';">
                    <ion-icon name="eye-outline" style="vertical-align: middle; margin-left: 0.25rem;"></ion-icon>
                    عرض التفاصيل
                </a>
            </td>

            <td>
                <form asp-controller="Project" asp-action="Reject" asp-route-Id="@Item.Id" class="d-inline">
                    <button type="submit" class="btn btn-danger px-4 btn-sm">
                        <i class="fa fa-times"></i> رفض نهائي
                    </button>
                </form>

                <a asp-controller="CoordinatorReport"
                   asp-action="ReCreateLicense"
                   asp-route-projectId="@Item.Id"
                   class="btn btn-success btn-sm ms-2">
                    <i class="fadeIn animated bx bx-refresh"></i> إعادة
                </a>
            </td>
        </tr>
    }
</tbody>
                </table>
            </div>
        </div>
    </div>
</div>

InvestLink/Views/CoordinatorReport/Update.cshtml
@model InvestLink_BLL.Models.CoordinatorReportVM

@using InvestLink_BLL.Interfaces
@using InvestLink_DAL.Entities
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> signInManager

@inject ICoordinatorReport icoordinatorReport;

@inject IEmployee iEmployee;

@* //----------ProjectId/IEmployeeId----------- *@

@inject IProjectCoordinator iProjectcoordinator;


@{

    var user = await signInManager.UserManager.GetUserAsync(signInManager.Context.User);
    var email = await signInManager.UserManager.GetEmailAsync(user);
    var iEmployeeId = iEmployee.GetIdByEmail(email);
}


@{
    ViewBag.Title = "Update";
}

<div class="card">
    <div class="card-body">
        <div class="border p-3 rounded">
            <h6 class="mb-0 text-uppercase">تعديل بيانات تقرير </h6>
            <hr>

      

            <form asp-controller="CoordinatorReport" asp-action="Update" enctype="multipart/form-data" class="row g-3">

                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="ProjectCoordinatorId" />
                <input type="hidden" asp-for="ImageName" />
                


                <div class="col-12">
                    <label asp-for="Description" class="form-label">الوصف</label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

               
            
                <div class="col-12">
                    <label asp-for="Image" class="form-label">صورة المرفق</label>

                    @if (Model != null && !string.IsNullOrEmpty(Model.ImageName))
                    {
                        <div class="mb-3 p-2 border rounded bg-light">
                            <p class="text-muted small mb-1">الملف الحالي:</p>

                            <a href="@Url.Content("~/Files/Doc/" + Model.ImageName)" target="_blank" class="btn btn-sm btn-info text-white">
                                <i class='bx bx-show'></i> عرض الملف الحالي
                            </a>

                            <input type="hidden" asp-for="ImageName" value="@Model.ImageName" />
                        </div>
                    }
                     
                    <div class="mt-2">
                        <input asp-for="Image" class="form-control" type="file" />
                        <span class="text-muted small">اترك هذا الحقل فارغاً إذا كنت لا تريد تغيير الصورة.</span>
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-12">
                    <div class="d-flex justify-content-center gap-2 mt-3">
                        <input type="submit" value="حفظ" class="btn btn-success px-4" />


                        <a asp-action="Index" class="btn btn-secondary btn-sm px-4">الرجوع </a>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>