InvestLink/Controllers/AdvertisementController.cs
using AutoMapper;
using InvestLink_BLL.Helper;
using InvestLink_BLL.Interfaces;
using InvestLink_BLL.Models;
using InvestLink_DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace InvestLink.Controllers
{
    public class AdvertisementController : Controller
    {
        #region Fields



        private readonly IAdvertisement advertisement;
        private readonly IEmployee employee;
        private readonly ILicense license;
        private readonly IMapper mapper;
        private readonly IToastNotification toastNotification;


        #endregion

        //-----------------------------------------
        #region Ctor
        public AdvertisementController(IAdvertisement advertisement,IEmployee employee,ILicense license, IMapper mapper, IToastNotification toastNotification)
        {

            this.advertisement = advertisement;
            this.employee = employee;
            this.license = license;
            this.mapper = mapper;
            this.toastNotification = toastNotification;

        }

        #endregion
        //--------------------------------------------------

        #region Actions
        [Authorize(Roles = "Investor,Admin,HeadOfServices")]
        public async Task<IActionResult> Index()
        {
            var data = await advertisement.GetAllAsync();

            var result = mapper.Map<IEnumerable<AdvertisementVM>>(data);
            return View(result);

        }

        public async Task<IActionResult> InvestorIndex()
        {
            var data = await advertisement.GetAllAsync();

            var result = mapper.Map<IEnumerable<AdvertisementVM>>(data);
            return View(result);
        }

        [HttpGet]
        public IActionResult Create(int EmployeeId)
        {

            var model = new AdvertisementVM();
            model.EmployeeId = EmployeeId;

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Create(AdvertisementVM obj)
        {
            try
            {
                var ImageName = FileUpLoader.UploaderFile(obj.Image, "Doc");
                obj.ImageName = ImageName;
                if (ModelState.IsValid == true)
                {
                    var data = mapper.Map<Advertisement>(obj);

                    await advertisement.CreateAsync(data);
                    toastNotification.AddSuccessToastMessage("تم   إنشاء إعلان بنجاح.");
                    return RedirectToAction("Index");
                }
                TempData["Meesage"] = "validation Error";
                toastNotification.AddErrorToastMessage(" يرجى التحقق من البيانات");
                return View(obj);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                toastNotification.AddErrorToastMessage("حدث خطأ غير متوقع.");
                return View(obj);
            }

        }
        [HttpGet]
        public async Task<IActionResult> Update(int Id)
        {
            var data = await advertisement.GetByIdAsync(Id);
            var result = mapper.Map<AdvertisementVM>(data);
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Update(AdvertisementVM obj)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    //1.فحص هل قام المستخدم برفع صورة جديدة؟
                    if (obj.Image != null)
                    {
                        // حالة: المستخدم اختار صورة جديدة
                        // نقوم برفع الصورة وحفظ الاسم الجديد
                        string fileName = FileUpLoader.UploaderFile(obj.Image, "Doc");
                        obj.ImageName = fileName;

                        // (اختياري) يمكنك هنا حذف الصورة القديمة لتوفير المساحة
                    }
                    else
                    {
                        // حالة: المستخدم لم يختر صورة (يريد إبقاء القديمة)
                        // يجب أن نجلب الاسم القديم من قاعدة البيانات حتى لا يتم حفظه كـ null
                        var oldEntity = await advertisement.GetByIdAsync(obj.Id);

                        // نضع الاسم القديم في الكائن الجديد
                        obj.ImageName = oldEntity.ImageName;
                    }
                    var data = mapper.Map<Advertisement>(obj);
                    await advertisement.UpdateAsync(data);
                    toastNotification.AddSuccessToastMessage("تم   تعديل بيانات  بنجاح.");
                    return RedirectToAction("Index");
                }
                TempData["Meesage"] = "validation Error";
                toastNotification.AddErrorToastMessage(" يرجى التحقق من البيانات");
                return View(obj);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                toastNotification.AddErrorToastMessage("حدث خطأ غير متوقع.");
                return View(obj);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var data = await advertisement.GetByIdAsync(Id);
            var result = mapper.Map<AdvertisementVM>(data);
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(AdvertisementVM obj)
        {
            try
            {
                var data = mapper.Map<Advertisement>(obj);
                await advertisement.DeleteAsync(data);
                toastNotification.AddSuccessToastMessage("تم   حذف  بنجاح.");
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                toastNotification.AddErrorToastMessage("حدث خطأ غير متوقع.");
                return View(obj);
            }
        }
       
      
       
        public async Task<IActionResult> Details(int Id)
        {
            var data = await advertisement.GetByIdAsync(Id);
            var result = mapper.Map<AdvertisementVM>(data);

            return View(result);
        }

    }
}

#endregion

InvestLink/Views/Advertisement/Create.cshtml
@model InvestLink_BLL.Models.AdvertisementVM
@using InvestLink_BLL.Models
@using InvestLink_DAL.Entities

@* //--------------------------------- *@
@using InvestLink_BLL.Interfaces
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> signInManager
@inject IEmployee iEmployee;
@{
    ViewBag.Title = "Create";
}

@{
    var user = await signInManager.UserManager.GetUserAsync(signInManager.Context.User);
    var email = await signInManager.UserManager.GetEmailAsync(user);
    var iEmployeeId = iEmployee.GetIdByEmail(email);

}


<div class="card">
    <div class="card-body">
        <div class="border p-3 rounded">
            <h6 class="mb-0 text-uppercase">إنشاء إعلان</h6>
            <hr>
            <form asp-controller="Advertisement" asp-action="Create" enctype="multipart/form-data" class="row g-3">

                <input type="hidden"  asp-for="EmployeeId" value="@iEmployeeId" />

                <div class="col-12">
                    <label  class="form-label">اسم الإعلان</label>
                    <input type="text" asp-for="Name" class="form-control">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-12">
                    <label class="form-label">صور أو ملف</label>
                    <input type="file" asp-for="Image" class="form-control">
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                
                <div class="col-12">
                    <label class="form-label">محتوى الإعلان</label>
                    <textarea class="form-control" asp-for="Description" rows="4" cols="4"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
               
                <div class="col-md-6">

                        <input type="submit" value="حفظ" class="btn btn-success waves-effect" />
                        <a asp-controller="Advertisement" asp-action="Index" class="btn btn-outline-secondary px-4">رجوع</a>
                  
                </div>
            </form>
        </div>
    </div>
</div>

InvestLink/Views/Advertisement/Delete.cshtml
@using InvestLink_BLL.Interfaces
@using Microsoft.AspNetCore.Identity
@model InvestLink_BLL.Models.AdvertisementVM

@inject SignInManager<IdentityUser> signInManager
@inject IEmployee iEmployee;

@{
    ViewBag.Title = "Delete";
}



@{
    var user = await signInManager.UserManager.GetUserAsync(signInManager.Context.User);
    var email = await signInManager.UserManager.GetEmailAsync(user);
    var iEmployeeId = iEmployee.GetIdByEmail(email);

}
<div class="card">
    <div class="card-body">
        <div class="border p-3 rounded">
            <h6 class="mb-0 text-uppercase">حذف إعلان</h6>
            <hr>
            <form asp-controller="Advertisement" asp-action="Delete" enctype="multipart/form-data" class="row g-3">

                <input type="hidden" value="1" asp-for="EmployeeId" />
                <div class="col-12">
                    <label class="form-label">اسم الإعلان</label>
                    <input type="text" asp-for="Name" class="form-control" readonly>
                </div>
                <div class="col-12">
                    <label class="form-label">صور أو ملف</label>
                    <input type="file" asp-for="Image" class="form-control" readonly>
                </div>

                <div class="col-12">
                    <label class="form-label">محتوى الإعلان</label>
                    <textarea class="form-control" asp-for="Description" rows="4" cols="4" readonly></textarea>
                </div>

                <div class="col-md-6">
                  
                        <input type="submit" value="حذف" class="btn btn-success waves-effect" />
                        <a asp-controller="Advertisement" asp-action="Index" class="btn btn-outline-secondary px-4">رجوع</a>
                   
                </div>
            </form>
        </div>
    </div>
</div>

InvestLink/Views/Advertisement/Details.cshtml
@model InvestLink_BLL.Models.AdvertisementVM



@{
    ViewBag.Title = "Details";
}





<div class="card">
    <div class="card-body">
        <div class="border p-3 rounded">
            <h6 class="mb-0 text-uppercase">تفاصيل تقرير </h6>
            <hr>

          

            <form asp-controller="Advertisement" asp-action="Details" enctype="multipart/form-data" class="row g-3">

                <input type="hidden" asp-for="Id" />

                <input type="hidden" asp-for="EmployeeId" />
                <input type="hidden" asp-for="ImageName" />
                <div class="col-12">
                    <label asp-for="Name" class="form-label">الوصف</label>
                    <textarea asp-for="Name" class="form-control" readonly></textarea>
                    
                </div>

                <div class="col-12">
                    <label class="form-label">محتوى الإعلان</label>
                    <textarea class="form-control" asp-for="Description" rows="4" cols="4" readonly></textarea>
                    
                </div>

                <div class="col-12 col-lg-12">
                    <label class="form-label">صورة </label>

                    @if (Model != null && !string.IsNullOrEmpty(Model.ImageName))
                    {
                        <div class="mt-2">
                            <a href="@Url.Content("~/Files/Doc/" + Model.ImageName)" target="_blank" class="form-control">
                                <i class='bx bx-show'></i> عرض الملف
                            </a>
                        </div>
                    }
                    else
                    {
                        <input type="text" class="form-control text-muted" value="لا يوجد ملف مرفق" readonly>
                    }
                </div>
         

            
                 
                

               
                <div class="col-6">
                    <div class="d-flex justify-content-start gap-2 mt-3">
                       
                        <a asp-action="Index" class="btn btn-secondary btn-sm px-4">الرجوع </a>

                    </div>
                </div>
            </form>
            
           
           
               
           
           
        </div>
    </div>
</div>

InvestLink/Views/Advertisement/Index.cshtml
@model IEnumerable<InvestLink_BLL.Models.AdvertisementVM>
@{
    ViewBag.Title = "Index ";
}


<h6 class="mb-0 text-uppercase"></h6>
<hr>
@if (!User.IsInRole("Investor"))
{
    <a asp-controller="Advertisement" asp-action="Create" class="btn btn-info waves-effect">
    <i class="fadeIn animated bx bx-pencil"></i>
</a>}
<br />
<br />


<div class="card">
    <div class="card-body">
        <table class="table mb-0 table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">اسم</th>
                    <th scope="col"> الوصف</th>
                    <th scope="col"> الاجراءات</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int Count = 0;
                }
                @foreach (var Item in Model)
                {
                    Count++;
                    <tr>
                        <th scope="row">
                            <div style="width: 40px; height: 40px; background: linear-gradient(135deg, rgba(79, 172, 254, 0.1) 0%, rgba(0, 242, 254, 0.1) 100%); border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: 700; color: #4facfe;">
                                @Count
                            </div>
                        </th>
                        <td>@Item.Name</td>
                        <td>@Item.Description</td>
                        

                        <td>
                            @if (!User.IsInRole("Investor"))
                            {
                                <a asp-controller="Advertisement" asp-action="Update" asp-route-Id=@Item.Id  class="btn btn-success waves-effect">
                                    <i class="fadeIn animated bx bx-refresh"></i>
                                </a>
                            }
                        </td>
                        <td>
                            <a asp-controller="Advertisement" asp-action="Details" asp-route-Id=@Item.Id  class="btn btn-secondary">
                                <i class="fadeIn animated bx bx-file-blank"></i>
                            </a>
                        </td>
                        <td>
                             @if (!User.IsInRole("Investor") )
                            {
                                <a asp-controller="Advertisement" asp-action="Delete" asp-route-Id=@Item.Id class="btn btn-danger waves-effect">
                                    <i class="fadeIn animated bx bx-trash-alt"></i>
                                </a>
                            }
                        </td>


                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

InvestLink/Views/Advertisement/Index1.cshtml
@model InvestLink_BLL.Models.AdvertisementVM


<div class="card">
    <div class="card-body">
        <div class="row align-items-center g-3">
            <div class="col-12 col-lg-6">
                <div class="d-lg-flex align-items-start gap-3">
                    <div class="cart-img text-center text-lg-start">
                        <img src="assets/images/products/02.png" class="rounded" width="130" alt="">
                    </div>
                    <div class="cart-detail text-center text-lg-start">
                        <form asp-controller="Advertisement" asp-action="Details" enctype="multipart/form-data" class="row g-3">
                            <input type="hidden" asp-for="EmployeeId" />
                            <input type="hidden" asp-for="Id" />

                            <div class="col-12">
                                <label class="form-label">اسم الإعلان</label>
                                <input type="text" asp-for="Name" class="form-control" readonly>
                            </div>

                            <div class="col-12">
                                <label class="form-label">صور أو ملف</label>
                                <input type="file" asp-for="Image" class="form-control" readonly>
                            </div>


                            <div class="col-12">
                                <label class="form-label">محتوى الإعلان</label>
                                <textarea class="form-control" asp-for="Description" rows="4" cols="4" readonly></textarea>
                            </div>

                            <a asp-controller="Advertisement" asp-action="Index" class="btn btn-danger">رجوع</a>


                            </form>
                        
                       
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-3">
                <div class="cart-action text-center">
                    <input type="number" class="form-control" value="2" min="1">
                </div>
            </div>
            <div class="col-12 col-lg-3">
                <div class="text-center">
                    <div class="d-flex gap-2 justify-content-center justify-content-lg-end">
                        <a href="javascript:;" class="btn btn-primary btn-ecomm"><i class='bx bx-x-circle'></i>Remove</a>
                        <a href="javascript:;" class="btn btn-outline-primary btn-ecomm"><i class='bx bx-heart mx-0'></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

InvestLink/Views/Advertisement/Update.cshtml
@model InvestLink_BLL.Models.AdvertisementVM
@using InvestLink_BLL.Interfaces
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> signInManager
@inject IEmployee iEmployee;

@{
    ViewBag.Title = "Update";
}



@{
    var user = await signInManager.UserManager.GetUserAsync(signInManager.Context.User);
    var email = await signInManager.UserManager.GetEmailAsync(user);
    var iEmployeeId = iEmployee.GetIdByEmail(email);

}


<div class="card">
    <div class="card-body">
        <div class="border p-3 rounded">
            <h6 class="mb-0 text-uppercase">تعديل إعلان</h6>
            <hr>
            <form asp-controller="Advertisement" asp-action="Update" enctype="multipart/form-data" class="row g-3">

                <input type="hidden" asp-for="EmployeeId" />
                <input type="hidden" asp-for="ImageName" />
                <div class="col-12">
                    <label class="form-label">اسم الإعلان</label>
                    <input type="text" asp-for="Name" class="form-control">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
          
                <div class="col-12">
                    <label asp-for="Image" class="form-label">صورة المرفق</label>

                  
                    @if (Model != null && !string.IsNullOrEmpty(Model.ImageName))
                    {
                        <div class="mb-3 p-2 border rounded bg-light">
                            <p class="text-muted small mb-1">الملف الحالي:</p>

                            <a href="@Url.Content("~/Files/Doc/" + Model.ImageName)" target="_blank" class="btn btn-sm btn-info text-white">
                                <i class='bx bx-show'></i> عرض الملف الحالي
                            </a>

                            <input type="hidden" asp-for="ImageName" value="@Model.ImageName" />
                        </div>
                    }

                
                    <div class="mt-2">
                        <input asp-for="Image" class="form-control" type="file" />
                        <span class="text-muted small">اترك هذا الحقل فارغاً إذا كنت لا تريد تغيير الصورة.</span>
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-12">
                    <label class="form-label">محتوى الإعلان</label>
                    <textarea class="form-control" asp-for="Description" rows="4" cols="4"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                      

                        <input type="submit" value="حفظ" class="btn btn-success waves-effect" />
                        <a asp-controller="Advertisement" asp-action="Index" class="btn btn-outline-secondary px-4">رجوع</a>
                    </div>
             
            </form>
        </div>
    </div>
</div>